USE [master]
GO

/****** Object:  Database [CoronaDB]    Script Date: 5/27/2020 12:07:52 PM ******/
CREATE DATABASE [CoronaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CoronaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CoronaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CoronaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CoronaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CoronaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CoronaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CoronaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CoronaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CoronaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CoronaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CoronaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CoronaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CoronaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CoronaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CoronaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CoronaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CoronaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CoronaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CoronaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CoronaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CoronaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CoronaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CoronaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CoronaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CoronaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CoronaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CoronaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CoronaDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CoronaDB] SET  MULTI_USER 
GO

ALTER DATABASE [CoronaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CoronaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CoronaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CoronaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CoronaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CoronaDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CoronaDB] SET  READ_WRITE 
GO


